import { Box, Typography, List, ListItem, Link } from '@mui/material';

export const Info = () => {
  return (
    <Box
      className='fade-in'
      display='flex'
      alignContent='center'
      justifyContent='center'
      flexDirection='column'
    >
      <Typography variant='h2' mb={2}>
        Garmin Indoor Activity Distance Editor
      </Typography>
      <Typography variant='body1'>
        This tool allows you to edit the distance of a TCX file, commonly
        generated by Garmin devices.
      </Typography>
      <Typography variant='body1'>
        This is useful for editing indoor activities such as indoor bike,
        treadmill, or ergometer where the GPS signal cannot track the distance.
      </Typography>
      <Typography mt={2}>How to use:</Typography>
      <List>
        <ListItem>
          <Typography>
            1. Navigate to{' '}
            <Link href='https://connect.garmin.com/modern/activities'>
              your activities on Garmin Connect.
            </Link>{' '}
            Choose the activity you want to edit. Click the gear icon in the top
            right corner and select <strong>Export to TCX</strong>.
          </Typography>
        </ListItem>
        <ListItem>
          <Typography>
            2. Upload the exported TCX file using the button below
          </Typography>
        </ListItem>
        <ListItem>
          <Typography>3. Enter the distance you want to set in km</Typography>
        </ListItem>
        <ListItem>
          <Typography>4. Download the new TCX file</Typography>
        </ListItem>
        <ListItem>
          <Typography>
            5. Use the{' '}
            <Link href='https://support.strava.com/hc/en-us/articles/216917857-Uploading-Manual-Activities'>
              following
            </Link>{' '}
            to upload your updated activity to Strava
          </Typography>
        </ListItem>
        <ListItem>
          <Typography>
            6. If you have any issues or requests, please{' '}
            <Link
              href='mailto:enquiries@sheamcdevitt.com
            ?subject=Issue/Rquest%20about%20tools.sheamcdevitt.com
            &body=I got a issue or request about tools.sheamcdevitt.com'
            >
              email me{' '}
            </Link>
            and if you find this tool useful, consider{' '}
            <Link href='https://www.buymeacoffee.com/personall'>
              buying me a coffee
            </Link>
            .
          </Typography>
        </ListItem>
      </List>
    </Box>
  );
};
